# Generated by Django 5.0.1 on 2024-01-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=40, verbose_name='Полное имя')),
                ('age', models.CharField(max_length=3, verbose_name='Возраст')),
                ('sex', models.CharField(max_length=5, verbose_name='Пол')),
                ('message', models.CharField(max_length=40, verbose_name='Сообщение')),
            ],
        ),
    ]
