# Generated by Django 5.0.1 on 2024-01-23 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=40, verbose_name='Полное имя')),
                ('group', models.CharField(max_length=10, verbose_name='Группа')),
                ('release_year', models.DateField(verbose_name='Выпуск')),
                ('feedback_text', models.CharField(max_length=200, verbose_name='Отзыв')),
            ],
        ),
        migrations.AlterField(
            model_name='feedback',
            name='age',
            field=models.IntegerField(verbose_name='Возраст'),
        ),
    ]
