# Generated by Django 5.0.1 on 2024-01-23 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_app', '0002_alumnireviews_alter_feedback_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnireviews',
            name='slogan',
            field=models.CharField(default='default', max_length=100, verbose_name='Слоган'),
        ),
    ]
