# Generated by Django 5.0.1 on 2024-01-23 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_app', '0003_alumnireviews_slogan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnireviews',
            name='feedback_text',
            field=models.CharField(max_length=400, verbose_name='Отзыв'),
        ),
    ]
